# Generated by Django 5.0.2 on 2026-03-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersummary',
            name='message_count_at_summary',
            field=models.IntegerField(default=0),
        ),
    ]
