# Generated by Django 5.0.2 on 2026-03-29 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chats_chats_user_id_01e3de_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'created_at'], name='chats_chats_user_id_cd9077_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'created_at'], name='chats_messa_session_bd07cf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', '-created_at'], name='chats_messa_session_acdddb_idx'),
        ),
    ]
