# Generated by Django 5.0.2 on 2026-03-30 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language_tag',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic')], db_index=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='language_tag',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ai_model',
            field=models.CharField(default='nemotron', max_length=50),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'language_tag', '-created_at'], name='chats_chats_user_id_d120c2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'language_tag', '-created_at'], name='chats_messa_session_c9eecc_idx'),
        ),
    ]
