# Generated by Django 5.0.2 on 2026-03-30 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(max_length=2000)),
                ('language_tag', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_index=True, max_length=5)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('source_session_id', models.IntegerField(blank=True, help_text='ChatSession ID used to generate this summary', null=True)),
                ('relevance_score', models.FloatField(default=1.0, help_text='Confidence score [0.0-1.0] for future ranking')),
                ('archived', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag; archived summaries remain in DB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_generated'],
                'indexes': [models.Index(fields=['user', 'archived', '-date_generated'], name='ai_usersumm_user_id_650a57_idx'), models.Index(fields=['user', 'language_tag', 'archived'], name='ai_usersumm_user_id_e3704d_idx')],
            },
        ),
    ]
