# Generated by Django 5.0.2 on 2026-03-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_auth_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verificationcode',
            new_name='users_verif_user_id_d66cd5_idx',
            old_name='users_verifi_user_id_code_idx',
        ),
        migrations.RenameIndex(
            model_name='verificationcode',
            new_name='users_verif_expires_4b338e_idx',
            old_name='users_verifi_expires_at_idx',
        ),
    ]
