# Generated by Django 5.0.2 on 2026-03-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_verifi_user_id_code_idx_users_verif_user_id_d66cd5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language_preference_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
